In [9]:
'''Evaluating Cars Based On Their Characteristics'''

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import preprocessing
from sklearn import cross_validation
from sklearn.ensemble import RandomForestClassifier
from sklearn.learning_curve import validation_curve

input_file = 'car.data'

# Reading the data
X = []
y = []
count = 0
with open(input_file, 'r') as f:
    for line in f.readlines():
        data = line[:-1].split(',')
        X.append(data)

X = np.array(X)

# convert String data to numerical
label_encoder = []
X_encoded = np.empty(X.shape)
for i, item in enumerate(X[0]):
    label_encoder.append(preprocessing.LabelEncoder())
    X_encoded[:, i] = label_encoder[-1].fit_transform(X[:, i])

X = X_encoded[:, :-1].astype(int)
y = X_encoded[:, -1]

# Build a Random Forest Classifier
params = {'n_estimators':200, 'max_depth': 8, 'random_state': 7}
classifier = RandomForestClassifier(**params)
classifier.fit(X, y)

# Cross Validation

accuracy = cross_validation.cross_val_score(classifier, X, y, scoring='accuracy', cv=3)
print('Accuracy of the classifier: ' + str(round(100 * accuracy.mean(), 2)) + '%')

# Testing encodign data on single instance
input_data = ['vhigh', 'vhigh', '2', '2', 'small', 'low']
input_data_encoded = [-1] * len(input_data)
for i, item in enumerate(input_data):
    input_data_encoded[i] = int(label_encoder[i].transform(input_data[i]))

input_data_encoded = np.array(input_data_encoded)

# Predict and Print Output for a particular datapoint
output_class =classifier.predict(input_data_encoded)
#print('Outputclass: ', label_encoder[-1].inverse_transform(output_class)[0])

'''Exctracting Validation Curves'''

classifier = RandomForestClassifier(max_depth=4, random_state=7)

parameter_grid = np.linspace(25, 200, 8).astype(int)
train_scores, validation_scores = validation_curve(classifier, X, y, 'n_estimators', parameter_grid, cv=5)
print('\n#### VALIDATION CURVE ####')
print('\nParam: n_estimators\nTraining scores:\n', train_scores)
print('\nParam: n_estimators\nValidation scores:\n', validation_scores)

# Plot the Curve
plt.figure()
plt.plot(parameter_grid, 100 * np.average(train_scores, axis=1), color='black')
plt.title('Training Curve')
plt.xlabel('Number of Estiamtors')
plt.ylabel('Accuracy')
#plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'car.data'

In [12]:
X = np.random.rand(5, 4)

In [18]:
X[0].shape

(4,)

In [15]:
print(X)

[[ 0.73066544  0.07423537  0.3315819   0.99440058]
 [ 0.22559091  0.03026632  0.17599552  0.07035996]
 [ 0.99304615  0.25038399  0.6779803   0.8191071 ]
 [ 0.59030893  0.52700493  0.23324613  0.90323461]
 [ 0.43492985  0.83894773  0.00692423  0.05343387]]


In [ ]:
print(X[0])

In [13]:
import numpy as np
x = np.array([3., 3., 5., 0.,  2., -100., 5., 2., 7, -3, -3, -4.])

In [14]:
print(set(x))

{0.0, 2.0, 3.0, 5.0, 7.0, -4.0, -100.0, -3.0}
